[package]
name = "vhsichdl"
version = "0.1.0"
edition = "2025"

[dependencies]
gtk = { version = "0.9.7", package = "gtk4", features = ["v4_8"] }
gtksourceview = { version = "0.9.1", package = "sourceview5" }
gio = "0.20.12"
